// SproutCore ViewBuilder Design Format v1.0
// WARNING: This file is automatically generated.  DO NOT EDIT.  Changes you
// make to this file will be lost.
Redbull.TestPage = SC.Page.design({
  mainView: SC.View.design({
    layout: {
      "top": 53,
      "left": 48,
      "right": 26,
      "bottom": 42
    },
    childViews: [SC.LabelView.design({
      layout: {
        "top": 25,
        "left": 362,
        "width": 218,
        "height": 132
      },
      value: "dork",
      backgroundColor: "#AAA"
    }),SC.LabelView.design({
      layout: {
        "top": 182,
        "left": 362,
        "width": 218,
        "height": 132
      },
      value: "dork",
      backgroundColor: "#BBB"
    }),SC.LabelView.design({
      layout: {
        "top": 26,
        "left": 123,
        "width": 218,
        "height": 132
      },
      value: "dork",
      backgroundColor: "#333"
    }), SC.LabelView.design({
      layout: {
        "top": 178,
        "left": 124,
        "width": 218,
        "height": 132
      },
      value: "dork",
      backgroundColor: "#A2A2A2"
    }), SC.LabelView.design({
      layout: {
        "top": 25,
        "left": 362,
        "width": 218,
        "height": 132
      },
      value: "dork",
      backgroundColor: "#AAA"
    }), SC.LabelView.design({
      layout: {
        "top": 328,
        "left": 123,
        "width": 218,
        "height": 132
      },
      value: "dork",
      backgroundColor: "#A2A2A2"
    }), SC.ButtonView.design({
      layout: {
        "top": 328,
        "left": 10,
        "width": 100,
        "height": 24
      },
      title: "dork",
      theme: 'capsule'
    })]
  }),
  pageName: "Redbull.TestPage"
});
