// SproutCore ViewBuilder Design Format v1.0
// WARNING: This file is automatically generated.  DO NOT EDIT.  Changes you
// make to this file will be lost.

Redbull.TestPage = SC.Page.design({mainView: SC.View.design({layout: {"top": 0,"left": 0,"right": 0,"bottom": 0},childViews: [SC.LabelView.design({layout: {"top": 229,"left": 121,"width": 100,"height": 100},value: "dork"}),SC.LabelView.design({layout: {"top": 29,"left": 692,"width": 155,"height": 75},value: "dork"}),SC.LabelView.design({layout: {"top": 29,"left": 692,"width": 155,"height": 75},value: "dork"})]}),pageName: "Redbull.TestPage"});
